"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Sparkles,
  Lightbulb,
  Stethoscope,
  Info,
} from "lucide-react";
import { analyze, type Insight } from "@/lib/ai/analyze";
import { buildSignalSeries } from "@/lib/dashboard/synth-data";
import { loadConnections } from "@/lib/integrations/storage";
import { cn } from "@/lib/utils";

interface AiInsightsProps {
  daysSinceStart: number;
}

const TONE_META: Record<
  Insight["tone"],
  { icon: React.ReactNode; pill: string; bar: string }
> = {
  informational: {
    icon: <Info className="h-4 w-4" />,
    pill: "bg-brand-50 text-brand-600",
    bar: "bg-brand-500",
  },
  suggestion: {
    icon: <Lightbulb className="h-4 w-4" />,
    pill: "bg-sunrise-100 text-sunrise-500",
    bar: "bg-sunrise-400",
  },
  referral: {
    icon: <Stethoscope className="h-4 w-4" />,
    pill: "bg-alert/10 text-alert",
    bar: "bg-alert",
  },
};

export function AiInsights({ daysSinceStart }: AiInsightsProps) {
  const [insights, setInsights] = useState<Insight[]>([]);
  const signals = useMemo(() => buildSignalSeries(), []);

  useEffect(() => {
    const connections = loadConnections();
    const generated = analyze({
      signals,
      connections,
      daysSinceStart,
    });
    setInsights(generated);
  }, [signals, daysSinceStart]);

  if (insights.length === 0) return null;

  return (
    <section className="glimpse-card p-6 relative overflow-hidden">
      <div className="absolute -right-10 -top-12 h-40 w-40 rounded-full bg-brand-50 blur-3xl pointer-events-none" />
      <div className="relative">
        <div className="flex items-center gap-2 mb-1">
          <span className="inline-flex items-center gap-1 rounded-full bg-brand-50 text-brand-600 px-2.5 py-0.5 text-xs font-medium uppercase tracking-wider">
            <Sparkles className="h-3 w-3" />
            Today&apos;s analysis
          </span>
        </div>
        <h2 className="text-xl font-semibold text-ink mt-1 mb-5">
          Patterns across the last two weeks
        </h2>

        <ul className="space-y-3">
          {insights.map((i) => (
            <li
              key={i.id}
              className="rounded-2xl bg-surface-alt border border-black/[0.06] p-4 flex gap-3"
            >
              <span
                aria-hidden
                className={cn("w-1 self-stretch rounded-full", TONE_META[i.tone].bar)}
              />
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1 flex-wrap">
                  <span
                    className={cn(
                      "inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium uppercase tracking-wider",
                      TONE_META[i.tone].pill,
                    )}
                  >
                    {TONE_META[i.tone].icon}
                    {i.tone === "informational"
                      ? "Observation"
                      : i.tone === "suggestion"
                        ? "Suggestion"
                        : "Worth a conversation"}
                  </span>
                </div>
                <p className="text-base font-semibold text-ink">{i.title}</p>
                <p className="text-sm text-ink-muted mt-1.5 leading-relaxed">
                  {i.body}
                </p>
              </div>
            </li>
          ))}
        </ul>

        <p className="mt-4 text-xs text-ink-muted leading-relaxed">
          Generated by the analysis layer from your recent signals and
          connected sensors. Glimpse describes patterns; it does not
          diagnose.
        </p>
      </div>
    </section>
  );
}
